openapi: 3.0.3

info:
  title: craftlab-voucher-api
  description: Generate voucher for craftlab's customers
  version: 'latest'

servers:
  - url: 'https://localhost:8080'

paths:
  '/ping':
    get:
      operationId: ping
      tags:
        - Health
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
  '/customers':
    get:
      operationId: getCustomers
      tags:
        - Customers
      responses:
        200:
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    #TODO: add customers CRUD endpoint as set in controller
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        mail:
          type: string